server:
  host: chat.freenode.net
  port: 6667
bot:
  nick: mynick
  user: somename
  realname: Fake Name
  password: password
  channels:
    - "#chat"
plugins:
  second-screen:
    pastebin-api-key: api-key
  twitter:
    consumer-key: 'KEY'
    consumer-secret: 'SECRET'
    access-token: 'TOKEN'
    access-token-secret: 'TOKENSECRET'
