server:
  host: chat.freenode.net
  port: 6667
bot:
  nick: bot_nick
  user: Cinch
  realname: FakeName
  password: password
  channels:
    - '#channel'
    - '#another_channel'
authentication:
  minimum-level: :v
  admin-level: :o
custom-log:
  file: './log/cinch_bot.log'
  level: :info
plugins:
  google:
    api: api-key
  second-screen:
    pastebin-api-key: APIKEY
  twitter:
    consumer-key: 'KEY'
    consumer-secret: 'SECRET'
    access-token: 'TOKEN'
    access-token-secret: 'TOKENSECRET'
  wolfram:
    api: api-key
