irc:
    nick: 'bot_nick'
twitter:
    consumer-key: 'KEY'
    consumer-secret: 'SECRET'
    access-token: 'TOKEN'
    access-token-secret: 'TOKENSECRET'

# server:
#   host: chat.freenode.net
#   port: 6667
# bot:
#   user: Cinch
#   realname: FakeName
#   password: password
#   channels:
#     - '#channel'
#     - '#another_channel'
# authentication:
#   minimum-level: :v
#   admin-level: :o
# custom-log:
#   file: './log/cinch_bot.log'
#   level: :info
# plugins:
#   google:
#     api: api-key
#   second-screen:
#     pastebin-api-key: APIKEY
#   strawpoll:
#     repeat_time: 60
#     repeat_count: 3
#     allow_pol: true
#   urban_dict:
#     max_length: 300
#   wikipedia:
#     max_length: 300
#   wolfram:
#     api: api-key
#     max_length: 300
