server:
  host: 'chat.freenode.net'
  port: 6667
bot:
  nick: 'dctvbot'
  user: 'Cinch'
  realname: 'DCTV Bot'
  password: 'password'
  channels:
    - '#chat'
plugins:
  second-screen:
    pastebin-api-key: 'apikey'
  twitter:
    consumer-key: 'KEY'
    consumer-secret: 'SECRET'
    access-token: 'TOKEN'
    access-token-secret: 'TOKENSECRET'
log-file: '/tmp/log/cinch/dctvbot.log'
