source 'https://rubygems.org'

gem 'cinch', '2.2.6'
gem 'cinch-authentication', '0.1.1'
gem 'cinch-identify', '1.7.0'
gem 'cinch-toolbox', '1.1.4'
gem 'cleverbot', :git => 'https://github.com/jalada/cleverbot.git'
gem 'httparty', '0.13.5'
gem 'json', '1.8.3'
gem 'time_sentence', '1.0.1'
gem 'activesupport', '4.2.4'
gem 'twitter', '5.15.0'
