source 'https://rubygems.org'

gem 'activesupport', '4.2.4'
gem 'cinch', '2.3.1'
gem 'cinch-authentication', '0.1.1'
gem 'cinch-identify', '1.7.0'
gem 'cinch-strawpoll', '0.0.9'
gem 'cinch-toolbox', '1.1.4'
gem 'cleverbot', :git => 'https://github.com/sapslaj/cleverbot.git'
gem 'google-search', '1.0.3'
gem 'httparty', '0.13.5'
gem 'json', '1.8.3'
gem 'time_sentence', '1.0.1'
gem 'twitter', '5.15.0'
gem 'wolfram-alpha', '0.3.1'
